### ISSUE TITLE
time-slider breaks in Firefox

### ISSUE THREAD

**Issue by pacesm** [EOX-A/d3.TimeSlider#13]
There is apparently a bug in the time-slider which breaks the time-slider in Firefox browser (v18) after using it (zooming in/out and moving time-line forth and back, brush changes and browser window resizing) for some time. 

The effect starts by small abrupt misalignments in the displayed data-items, data-ticks, and time-line ticks. 

Once it appears, soon or later, all the displayed items disappear leaving just an empty time-slider widget with single black horizontal line across. 

This bug appears randomly and no obvious cause has been observed.

**Comment by santilland** [comment]
This could be related to the redrawing strategy previously used and could maybe be solved in the new major release. Will need to look into it.

**Comment by Schpidi** [comment]
I agree, this seems to be resolved. At least it isn't happening in https://github.com/eoxc/eoxc where we use the timeslider quite extensively.

**Comment by Schpidi** [comment]
Closing as it seems resolved. Please reopen if neccesary.
