### ISSUE TITLE
Time-slider breaks if collection name contains colon character `:`

### ISSUE THREAD

**Issue by pacesm** [EOX-A/d3.TimeSlider#17]
As the title says, the time-slider is not able coop with collection name containing one or more colon characters `:`. 

If, in the client, a layer with the above described document is selected, the time slider crashes (reported by the browser console) and either it does not pop-up (if it is supposed to be displayed) or does not show any tick for the selected layer (if already displayed). 

This pose a serious issue is it prevents use of URNs as collection identifies.

**Comment by santilland** [comment]
Solved in #18 (id not longer used in element)
