### ISSUE TITLE
Time selection with no duration not visible

### ISSUE THREAD

**Issue by Schpidi** [EOX-A/d3.TimeSlider#19]
This happens when selecting an entry with no duration/same start and stop. It should still be visible somehow what is selected on the time slider.

**Comment by pacesm** [comment]
IMO, a zero-duration period should be displayed as a single time point (e.g., by a vertical line) rather than collapse to a zero-width box which disappears from the time-line.

**Comment by constantinius** [comment]
This issue is addressed in #22

**Comment by santilland** [comment]
Solved in #18
