### ISSUE TITLE
Limit panning

### ISSUE THREAD

**Issue by Schpidi** [EOX-A/d3.TimeSlider#20]
While it is possible to limit zooming, user can still pan to periods outside the valid area. It would be great to limit panning as well.

**Comment by santilland** [comment]
You are in luck, implementation in d3 was merged 15 days ago :)
https://github.com/d3/d3/pull/2019

**Comment by santilland** [comment]
Solved in #18, see https://github.com/EOX-A/d3.TimeSlider#constrain---boolean
